# Generated by Django 5.2.16 on 2026-09-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_materialevidencereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialprocessingtask',
            name='attemptCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialprocessingtask',
            name='executionBackend',
            field=models.CharField(db_index=True, default='runtime', max_length=16),
        ),
        migrations.AddField(
            model_name='materialprocessingtask',
            name='leaseEpoch',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialprocessingtask',
            name='leaseExpiresAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialprocessingtask',
            name='leaseOwner',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
