# Generated by Django 5.2.16 on 2026-09-23 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_agentrun_pre_admission_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelQuotaDomain',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=64, unique=True)),
                ('maxConcurrent', models.PositiveSmallIntegerField()),
                ('enabled', models.BooleanField(default=False)),
                ('cooldownUntilMs', models.BigIntegerField(default=0)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('maxConcurrent__gte', 1), ('maxConcurrent__lte', 64)), name='model_quota_domain_concurrency_valid')],
            },
        ),
        migrations.AddField(
            model_name='providercredential',
            name='quotaDomain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credentials', to='app_core.modelquotadomain'),
        ),
    ]
