# Generated by Django 5.2.16 on 2026-09-08 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_materialprocessingtask_attemptcount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialProcessor',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('specification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_core.processingspecification')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialStagedObject',
            fields=[
                ('storageKey', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('sizeBytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=71)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_core.materialprocessingtask')),
            ],
        ),
    ]
