# Generated by Django 5.2.16 on 2026-09-26 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0004_modelquotadomain_providercredential_quotadomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedOperationReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=32)),
                ('operationId', models.CharField(max_length=128)),
                ('requestDigest', models.CharField(max_length=64)),
                ('sessionId', models.CharField(max_length=64)),
                ('agentRunId', models.CharField(max_length=64, null=True)),
                ('turnId', models.CharField(max_length=64, null=True)),
                ('acceptedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_core.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'workspace', 'command', 'operationId'), name='hosted_operation_scope_unique'), models.CheckConstraint(condition=models.Q(models.Q(('agentRunId__isnull', True), ('command', 'createSession'), ('turnId__isnull', True)), models.Q(('agentRunId__isnull', False), ('command', 'submitMessage'), ('turnId__isnull', False)), _connector='OR'), name='hosted_operation_result_valid')],
            },
        ),
    ]
