# Generated by Django 5.2.16 on 2026-09-28 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_hosted_operation_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptOutputCapture',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_core.sessionevent')),
                ('executionId', models.CharField(max_length=160)),
                ('sha256', models.CharField(max_length=71)),
                ('byteLength', models.PositiveBigIntegerField()),
                ('chunkSize', models.PositiveIntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('purgedAt', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptOutputChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('data', models.BinaryField()),
                ('sha256', models.CharField(max_length=71)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='app_core.transcriptoutputcapture')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('capture', 'index'), name='unique_transcript_output_chunk')],
            },
        ),
    ]
