# Generated by Django 5.2.16 on 2026-09-30 11:51

import app_core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_transcript_output_capture'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinitionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AgentDefinitionVersion',
            fields=[
                ('id', models.CharField(default=app_core.models.new_agent_definition_version_id, max_length=64, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
                ('instructions', models.TextField(blank=True, default='')),
                ('avatar_kind', models.CharField(default='centaeris', max_length=16)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('id', models.CharField(default=app_core.models.new_agent_definition_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=128)),
                ('instructions', models.TextField(blank=True, default='')),
                ('avatar_kind', models.CharField(default='centaeris', max_length=16)),
                ('status', models.CharField(default='active', max_length=16)),
                ('availability_scope', models.CharField(default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_definitions', to='app_core.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='app_core.agentdefinition'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('workspace', 'owner', 'definition'), name='agent_definition_owner_unique'),
        ),
        migrations.AddField(
            model_name='agentdefinitionmember',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_grants', to='app_core.agentdefinition'),
        ),
        migrations.AddField(
            model_name='agentdefinitionmember',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_definition_grants', to='app_core.workspacemembership'),
        ),
        migrations.AddField(
            model_name='agentdefinitionversion',
            name='definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='app_core.agentdefinition'),
        ),
        migrations.AddField(
            model_name='agentdefinitionversion',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentdefinition',
            name='published_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='app_core.agentdefinitionversion'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='definition_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_runs', to='app_core.agentdefinitionversion'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinitionmember',
            constraint=models.UniqueConstraint(fields=('definition', 'membership'), name='agent_definition_member_unique'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinitionversion',
            constraint=models.UniqueConstraint(fields=('definition', 'version'), name='agent_definition_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinitionversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gt', 0)), name='agent_definition_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinitionversion',
            constraint=models.CheckConstraint(condition=models.Q(('avatar_kind__in', ('centaeris', 'banana'))), name='agent_definition_version_avatar'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('active', 'disabled'))), name='agent_definition_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('availability_scope__in', ('none', 'workspace', 'members'))), name='agent_definition_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='agentdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('avatar_kind__in', ('centaeris', 'banana'))), name='agent_definition_avatar_valid'),
        ),
    ]
