# Generated by Django 5.2.16 on 2026-09-08 15:46

import json
import django.db.models.deletion
from django.db import migrations, models


def preserve_recorded_projection(apps, schema_editor):
    Receipt = apps.get_model("app_core", "MaterialEvidenceReceipt")
    for row in Receipt.objects.iterator():
        row.modelProjection = {"text": [row.responseText], "structuredContent": json.loads(row.responseText)}
        row.save(update_fields=["modelProjection"])


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0006_platform_material_cutover'),
    ]

    operations = [
        migrations.AddField(model_name='materialevidencereceipt', name='modelProjection', field=models.JSONField(null=True)),
        migrations.RunPython(preserve_recorded_projection, migrations.RunPython.noop),
        migrations.AlterField(model_name='materialevidencereceipt', name='modelProjection', field=models.JSONField()),
        migrations.CreateModel(
            name='MaterialResultSnapshot',
            fields=[
                ('id', models.CharField(max_length=96, primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('sha256', models.CharField(max_length=71)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materialResult', to='app_core.sessionevent')),
            ],
        ),
    ]
