# Generated by Django 5.2.16 on 2026-09-30 13:42

import app_core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0007_agent_definitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdefinition',
            name='plugin_names',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='agentdefinitionversion',
            name='plugin_activation',
            field=models.JSONField(default=app_core.models.empty_plugin_activation),
        ),
        migrations.CreateModel(
            name='AgentConnectorCredentialApproval',
            fields=[
                ('id', models.CharField(default=app_core.models.new_agent_connector_approval_id, max_length=64, primary_key=True, serialize=False)),
                ('plugin_name', models.CharField(max_length=64)),
                ('server_id', models.CharField(max_length=64)),
                ('resource_path', models.CharField(max_length=255)),
                ('resource_digest', models.CharField(max_length=71)),
                ('credential_version', models.PositiveIntegerField()),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_approvals', to='app_core.mcpbearercredential')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connector_approvals', to='app_core.agentdefinition')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connector_approvals', to='app_core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='AgentConnectorBinding',
            fields=[
                ('id', models.CharField(default=app_core.models.new_agent_connector_binding_id, max_length=64, primary_key=True, serialize=False)),
                ('plugin_name', models.CharField(max_length=64)),
                ('server_id', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connector_bindings', to='app_core.agentdefinition')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connector_bindings', to='app_core.workspace')),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bindings', to='app_core.agentconnectorcredentialapproval')),
            ],
        ),
        migrations.AddConstraint(
            model_name='agentconnectorcredentialapproval',
            constraint=models.CheckConstraint(condition=models.Q(('credential_version__gt', 0)), name='connector_approval_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='agentconnectorbinding',
            constraint=models.UniqueConstraint(fields=('workspace', 'definition', 'plugin_name', 'server_id'), name='agent_connector_binding_unique'),
        ),
    ]
