# Generated by Django 5.2.16 on 2026-09-30 16:14

import app_core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_assistant_connector_authority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessApplication',
            fields=[
                ('id', models.CharField(default=app_core.models.new_business_app_id, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_business_apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agentrun',
            name='acting_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_runs', to='app_core.businessapplication'),
        ),
        migrations.AddField(
            model_name='hostedoperationreceipt',
            name='acting_app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_receipts', to='app_core.businessapplication'),
        ),
        migrations.CreateModel(
            name='UserAppDelegation',
            fields=[
                ('id', models.CharField(default=app_core.models.new_app_delegation_id, max_length=64, primary_key=True, serialize=False)),
                ('membership_ref', models.CharField(editable=False, max_length=64)),
                ('issuer', models.CharField(default='centaeris-workspace', editable=False, max_length=100)),
                ('audience', models.CharField(default='centaeris-workspace-api', editable=False, max_length=100)),
                ('scopes', models.JSONField()),
                ('token_digest', models.CharField(editable=False, max_length=71, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations', to='app_core.businessapplication')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_delegations', to='app_core.agentdefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_delegations', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='app_delegations', to='app_core.workspace')),
            ],
        ),
        migrations.AddField(
            model_name='agentrun',
            name='app_delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_runs', to='app_core.userappdelegation'),
        ),
        migrations.AddField(
            model_name='hostedoperationreceipt',
            name='app_delegation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_receipts', to='app_core.userappdelegation'),
        ),
        migrations.AddConstraint(
            model_name='agentrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('acting_app__isnull', True), ('app_delegation__isnull', True)), models.Q(('acting_app__isnull', False), ('app_delegation__isnull', False)), _connector='OR'), name='agent_run_app_origin_valid'),
        ),
        migrations.AddConstraint(
            model_name='businessapplication',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('pending', 'active', 'revoked'))), name='business_app_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='userappdelegation',
            constraint=models.CheckConstraint(condition=models.Q(('membership_ref', ''), _negated=True), name='app_delegation_membership_required'),
        ),
    ]
